# Generated by Django 3.1.3 on 2020-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('like', models.IntegerField(null=True)),
                ('shortDesk', models.TextField(null=True)),
                ('desk', models.TextField(null=True)),
            ],
        ),
    ]
