# Generated by Django 3.1.3 on 2020-12-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201214_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desk',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shortDesk',
            new_name='shortDesc',
        ),
    ]
