# Generated by Django 3.1.3 on 2020-12-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201214_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.FileField(upload_to='app/static/uploads/video')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.FileField(upload_to='app/static/uploads/image'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='videos',
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.video')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(related_name='productVideo', through='app.ProductVideo', to='app.Video'),
        ),
    ]
