# Generated by Django 3.1.3 on 2021-01-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201214_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='oui', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
