# Generated by Django 3.1.3 on 2021-01-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210102_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.FileField(upload_to='app/static/uploads/image'),
        ),
    ]
