# Generated by Django 3.1.3 on 2021-01-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210102_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default='oui', upload_to=''),
        ),
    ]
