# Generated by Django 3.1.6 on 2021-02-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210211_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
