# Generated by Django 3.1.6 on 2021-02-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210211_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='name',
        ),
    ]
